# Generated by Django 4.2.8 on 2024-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="hari", max_length=100),
            preserve_default=False,
        ),
    ]
